# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7820f2d280865e751171d6ffa22651c16732089d41ea5980f459493d39b9daca447e1e563f97049e86d69cb8f2a05477c0c99045c450285b621e07cfebbe4adb

test:
  secret_key_base: 85c19cdb1d2af76f7da22b1f2ae9c6e813b483e7a1d4edef772e94a2e1a04cbddb1543dbb21a13c1ffcd02866de43280887a2802d184e05e179d3c9331ac559a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
